// Country list for the Contact form. { name, iso2, dial } — dial includes '+'.
// Selecting a country auto-fills the dial code on the phone field.
export const COUNTRIES = [
  { name: 'Afghanistan', iso2: 'AF', dial: '+93' },
  { name: 'Albania', iso2: 'AL', dial: '+355' },
  { name: 'Algeria', iso2: 'DZ', dial: '+213' },
  { name: 'Argentina', iso2: 'AR', dial: '+54' },
  { name: 'Australia', iso2: 'AU', dial: '+61' },
  { name: 'Austria', iso2: 'AT', dial: '+43' },
  { name: 'Bahrain', iso2: 'BH', dial: '+973' },
  { name: 'Bangladesh', iso2: 'BD', dial: '+880' },
  { name: 'Belgium', iso2: 'BE', dial: '+32' },
  { name: 'Bhutan', iso2: 'BT', dial: '+975' },
  { name: 'Brazil', iso2: 'BR', dial: '+55' },
  { name: 'Bulgaria', iso2: 'BG', dial: '+359' },
  { name: 'Canada', iso2: 'CA', dial: '+1' },
  { name: 'Chile', iso2: 'CL', dial: '+56' },
  { name: 'China', iso2: 'CN', dial: '+86' },
  { name: 'Colombia', iso2: 'CO', dial: '+57' },
  { name: 'Croatia', iso2: 'HR', dial: '+385' },
  { name: 'Czech Republic', iso2: 'CZ', dial: '+420' },
  { name: 'Denmark', iso2: 'DK', dial: '+45' },
  { name: 'Egypt', iso2: 'EG', dial: '+20' },
  { name: 'Estonia', iso2: 'EE', dial: '+372' },
  { name: 'Finland', iso2: 'FI', dial: '+358' },
  { name: 'France', iso2: 'FR', dial: '+33' },
  { name: 'Germany', iso2: 'DE', dial: '+49' },
  { name: 'Ghana', iso2: 'GH', dial: '+233' },
  { name: 'Greece', iso2: 'GR', dial: '+30' },
  { name: 'Hong Kong', iso2: 'HK', dial: '+852' },
  { name: 'Hungary', iso2: 'HU', dial: '+36' },
  { name: 'Iceland', iso2: 'IS', dial: '+354' },
  { name: 'India', iso2: 'IN', dial: '+91' },
  { name: 'Indonesia', iso2: 'ID', dial: '+62' },
  { name: 'Iran', iso2: 'IR', dial: '+98' },
  { name: 'Iraq', iso2: 'IQ', dial: '+964' },
  { name: 'Ireland', iso2: 'IE', dial: '+353' },
  { name: 'Israel', iso2: 'IL', dial: '+972' },
  { name: 'Italy', iso2: 'IT', dial: '+39' },
  { name: 'Japan', iso2: 'JP', dial: '+81' },
  { name: 'Jordan', iso2: 'JO', dial: '+962' },
  { name: 'Kenya', iso2: 'KE', dial: '+254' },
  { name: 'Kuwait', iso2: 'KW', dial: '+965' },
  { name: 'Malaysia', iso2: 'MY', dial: '+60' },
  { name: 'Maldives', iso2: 'MV', dial: '+960' },
  { name: 'Mexico', iso2: 'MX', dial: '+52' },
  { name: 'Nepal', iso2: 'NP', dial: '+977' },
  { name: 'Netherlands', iso2: 'NL', dial: '+31' },
  { name: 'New Zealand', iso2: 'NZ', dial: '+64' },
  { name: 'Nigeria', iso2: 'NG', dial: '+234' },
  { name: 'Norway', iso2: 'NO', dial: '+47' },
  { name: 'Oman', iso2: 'OM', dial: '+968' },
  { name: 'Pakistan', iso2: 'PK', dial: '+92' },
  { name: 'Philippines', iso2: 'PH', dial: '+63' },
  { name: 'Poland', iso2: 'PL', dial: '+48' },
  { name: 'Portugal', iso2: 'PT', dial: '+351' },
  { name: 'Qatar', iso2: 'QA', dial: '+974' },
  { name: 'Romania', iso2: 'RO', dial: '+40' },
  { name: 'Russia', iso2: 'RU', dial: '+7' },
  { name: 'Saudi Arabia', iso2: 'SA', dial: '+966' },
  { name: 'Singapore', iso2: 'SG', dial: '+65' },
  { name: 'South Africa', iso2: 'ZA', dial: '+27' },
  { name: 'South Korea', iso2: 'KR', dial: '+82' },
  { name: 'Spain', iso2: 'ES', dial: '+34' },
  { name: 'Sri Lanka', iso2: 'LK', dial: '+94' },
  { name: 'Sweden', iso2: 'SE', dial: '+46' },
  { name: 'Switzerland', iso2: 'CH', dial: '+41' },
  { name: 'Taiwan', iso2: 'TW', dial: '+886' },
  { name: 'Thailand', iso2: 'TH', dial: '+66' },
  { name: 'Turkey', iso2: 'TR', dial: '+90' },
  { name: 'Ukraine', iso2: 'UA', dial: '+380' },
  { name: 'United Arab Emirates', iso2: 'AE', dial: '+971' },
  { name: 'United Kingdom', iso2: 'GB', dial: '+44' },
  { name: 'United States', iso2: 'US', dial: '+1' },
  { name: 'Vietnam', iso2: 'VN', dial: '+84' },
]
